# Generated by Django 4.1.1 on 2023-06-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodguide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='rating',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
