# Generated by Django 4.1.1 on 2023-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodguide', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='star_rating',
            field=models.IntegerField(default=5),
        ),
    ]
